#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Hayato Tsukagoshi
# SPDX-License-Identifiler: BSD-3-Clause

import syss

ans = 0
for line in sys.stdin:
	try:
		ans += int(line)
	except:
		ans += float(line)

print(ans)
